---

# ansible-playbook -K -D -i inventory/hosts.yml playbook_server.yml

- name: OpenVPN Client-to-Site
  hosts: all   # should be limited
  become: true
  gather_facts: true
  module_defaults:
    ansible.builtin.setup:
      gather_subset: ['distribution']
  roles:
    - ansibleguy.infra_openvpn
