---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

collections:
  - 'community.general'

roles:
  - src: 'ansibleguy.infra_pki'
  - src: 'ansibleguy.infra_nftables'
