---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

collections:
  - 'community.general'
  - 'ansible.posix'

roles:
  - name: 'oxlorg.pki'
    src: 'git+https://github.com/O-X-L/ansible-role-pki'

  - name: 'oxlorg.nftables'
    src: 'git+https://github.com/O-X-L/ansible-role-nftables'
