---

- name: OpenVPN | Checking config
  ansible.builtin.assert:
    that:
      - openvpn is defined
      - openvpn.instances is defined
      - OVPN_CONFIG.instances | is_dict
      - OVPN_CONFIG.instances | length > 0
      - OVPN_CONFIG.download in OVPN_HC.options.download
  tags: always

- name: OpenVPN | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"

- name: OpenVPN | Cleaning up temporary password files \#1
  ansible.builtin.shell: "ls {{ tmp_pwd_file_prefix }}*"
  args:
    executable: '/bin/bash'
  delegate_to: localhost
  become: false
  changed_when: false
  register: ovpn_pwd_files

- name: OpenVPN | Cleaning up temporary password files \#2
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ ovpn_pwd_files.stdout_lines }}"
  delegate_to: localhost
  become: false
  changed_when: false
