---

- name: OpenVPN | Checking config
  ansible.builtin.assert:
    that:
      - openvpn is defined
      - openvpn.instances | length > 0
  tags: always

- name: OpenVPN | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"
