---

- name: "OpenVPN | Server {{ server_name }} | Client {{ client.name }} | Remove Certificate"
  ansible.builtin.include_tasks: debian/client/cert/remove.yml

- name: "OpenVPN | Server {{ server_name }} | Client {{ client.name }} | Add Certificate"
  ansible.builtin.include_tasks: debian/client/cert/add.yml
