---

dependency:
  name: galaxy
#  options:
#    requirements-file: 'requirements.yml'
driver:
  name: docker
platforms:
  - name: test-ag-ovpn-tester
    docker_networks:
      - name: 'test-ag-ovpn'
        ipam_config:
          - subnet: '192.168.N.0/24'
            gateway: '192.168.N.254'
    networks:
      - name: 'test-ag-ovpn'
        ipv4_address: '192.168.N.1'
    groups: [grp_tester]

    # docker config
    docker_host: 'tcp://molecule-docker.local:2375'
    purge_networks: true
    image: 'debian:11-slim'
    dockerfile: 'Dockerfile_debian11_systemd.j2'
    build_image: yes
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

  - name: test-ag-ovpn-1
    networks:
      - name: 'test-ag-ovpn'
        ipv4_address: '192.168.N.2'
    groups: [grp_targets]

    # docker config
    docker_host: 'tcp://molecule-docker.local:2375'
    purge_networks: true
    image: 'debian:11-slim'
    dockerfile: 'Dockerfile_debian11_systemd.j2'
    build_image: yes
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: '/tmp'
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify  # MUST NOT make changes
    - idempotence
    - check
    - destroy
