---

- name: OpenVPN | Backup | Adding service & timer
  ansible.builtin.template:
    src: "templates/etc/systemd/system/backup-openvpn.{{ item }}.j2"
    dest: "/etc/systemd/system/{{ OVPN_CONFIG.backup.service }}.{{ item }}"
    owner: 'root'
    group: 'root'
    mode: 0644
  when: OVPN_CONFIG.backup.enable | bool
  loop:
    - 'service'
    - 'timer'

- name: OpenVPN | Backup | Adding directory
  ansible.builtin.file:
    state: directory
    path: "{{ OVPN_CONFIG.path.backup }}"
    owner: 'root'
    group: 'root'
    mode: 0750
  when: OVPN_CONFIG.backup.enable | bool

- name: OpenVPN | Backup | Enabling & Starting timer
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ OVPN_CONFIG.backup.service }}.timer"
    state: started
    enabled: true
  when: OVPN_CONFIG.backup.enable | bool

- name: OpenVPN | Backup | Disabling & Stopping timer
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ OVPN_CONFIG.backup.service }}.timer"
    state: stopped
    enabled: false
  when: not OVPN_CONFIG.backup.enable | bool
  register: ovpn_backup_disable
  failed_when:
    - ovpn_backup_disable.failed
    - "'does not exist' not in ovpn_backup_disable.msg"
    - "'Could not find' not in ovpn_backup_disable.msg"
