---

# todo: option to allow firewall to be managed by role (nftables)

- name: OpenVPN | Setup
  ansible.builtin.import_tasks: debian/setup.yml

- name: OpenVPN | Backup
  ansible.builtin.import_tasks: debian/backup.yml

- name: OpenVPN | Server instances
  ansible.builtin.import_tasks: debian/instance/main.yml
