---

# add directories
# add server config
# enable & start service
# add auth-wrapper (instance-specific auth-providers/-config)
# add auth-providers
# initialize pki

- name: "OpenVPN | Server {{ server_name }} | Add | Validating config"
  ansible.builtin.assert:
    that:
      - server.ips | ensure_list > 0
      - server.auth_providers | ensure_list > 0
      - server.auth_providers | ensure_list | length == server.auth_providers | ensure_list | intersect(OVPN_HC.options.auth_providers) | length  # all providers are supported
      - server.proto in OVPN_HC.options.proto
      - server.port | int > 0
      - server.port | int < 65536
      - server.log_level | int >= 0
      - server.log_level | int < 12
      - "' ' in server.keepalive"

- name: "OpenVPN | Server {{ server_name }} | Add | Directories"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ OVPN_HC.user }}"
    group: "{{ server.group_read }}"
    mode: 750
  loop:
    - "{{ server_base_dir }}"
    - "{{ server_base_dir }}/{{ OVPN_HC.dir.profile }}"
    - "{{ server_base_dir }}/{{ OVPN_HC.dir.pki.base }}"

- name: "OpenVPN | Server {{ server_name }} | Add | Config"
  ansible.builtin.template:
    src: 'templates/etc/openvpn/instance/server.conf.j2'
    dest: "{{ server_base_dir }}/server.conf"
    owner: "{{ OVPN_HC.user }}"
    group: "{{ server.group_read }}"
    mode: 0440
  register: ovpn_server_config  # todo: restart with prompt

- name: "OpenVPN | Server {{ server_name }} | Add | PKI"
  ansible.builtin.include_tasks: debian/instance/pki.yml
  when: "'certificate' in server.auth_providers | ensure_list"

# todo: ip-wrapper
# todo: nat & nftables option (with simplified ruleset definition)
