---

- name: "OpenVPN | Server {{ server_name }} | Add | PKI | Checking if initialized"
  ansible.builtin.stat:
    path: "{{ server_base_dir }}/{{ OVPN_HC.dir.pki.private }}/ca.{{ OVPN_HC.ext.key }}"
  register: ovpn_pki_init

# NOTE: needed for scripted actions like automated crl-update
- name: "OpenVPN | Server {{ server_name }} | Add | PKI | Saving passwords"
  ansible.builtin.copy:
    content: "{{ item.pwd }}"
    dest: "{{ server_base_dir }}/{{ OVPN_HC.dir.pki.root }}/{{ item.file }}"
    mode: 0400  # if someone is already root - all hope is lost anyway
    owner: 'root'
    group: 'root'
  no_log: true
  with_items:
    - {pwd: "{{ server.pki.pwd.ca }}", file: "{{ OVPN_HC.file.pwd.ca }}"}
    - {pwd: "{{ server.pki.pwd.server }}", file: "{{ OVPN_HC.file.pwd.srv }}"}
    - {pwd: "{{ server.pki.pwd.client }}", file: "{{ OVPN_HC.file.pwd.cli }}"}
  when: not ovpn_pki_init.stat.exists

- name: "OpenVPN | Server {{ server_name }} | Add | PKI | Initializing"
  ansible.builtin.include_role:
    name: ansibleguy.infra_pki
  vars:
    pki:
      purge: false
      save_passwords: true
      manage:
        webserver: false

      crl_distribution:
        enable: false

      backup:
        enable: false  # covered by openvpn backup-job

      vars:
        algo: "{{ server.pki.algo }}"
        curve: "{{ server.pki.curve }}"
        digest: "{{ server.pki.digest }}"
        req_org: "{{ server.pki.org }}"
        req_ou: "{{ server.pki.ou }}"
        req_email: "{{ server.pki.email }}"
        req_country: "{{ server.pki.country }}"
        req_province: "{{ server.pki.province }}"

      instances:
        pki:
          path_base: "{{ server_base_dir }}"
          ca_cn: "OpenVPN-Root-CA-{{ server_name }}"
          pwd_ca: "{{ server.pki.pwd.ca }}"
          group_read: "{{ server.group_read }}"

          vars:
            ca_expire: "{{ server.pki.runtime_days.ca }}"
            cert_expire: "{{ server.pki.runtime_days.ca }}"  # sub-ca

          sub_cas:
            openvpn:
              pwd_ca: "{{ server.pki.pwd.ca }}"
              ca_cn: "{{ server.pki.cn.ca | replace(' ', '-') | replace('$server_name', server_name | capitalize) }}"
              vars:
                ca_expire: "{{ server.pki.runtime_days.ca }}"
                cert_expire: "{{ server.pki.runtime_days.client }}"
                key_size: "{{ server.pki.key_size }}"
              cert_no_pass: false  # also create encrypted keys
              export:
                unencrypted: true
                chain: true
                pkcs12: true
  when: not ovpn_pki_init.stat.exists
