---

- name: "OpenVPN | Server {{ server_name }} | Client {{ client.name }} | Remove TOTP-Token"
  ansible.builtin.include_tasks: debian/client/totp/remove.yml

- name: "OpenVPN | Server {{ server_name }} | Client {{ client.name }} | Add TOTP-Token"
  ansible.builtin.include_tasks: debian/client/totp/add.yml
